template: templates/loz-script-project.yaml
overrides:
  artifacts:
    - type: script
      version: 1.13.3
      build_script:
        repo_name: linux-on-ibm-z-scripts
        path: src/build.sh
        docker_image: ubuntu:22.04
